version: '3.9'

services:
  proxy:
    container_name: campus-proxy
    image: campus-proxy:1.0.0
    build:
      context: ./docker/proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    container_name: campus-db
    image: "campus-db:1.0.0"
    build:
      context: ./docker/db-mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: campus
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: campus
  
  pma:
    container_name: campus-pma
    image: campus-pma:1.0.0
    build:
      context: ./docker/pma
      dockerfile: Dockerfile
    environment:
        VIRTUAL_HOST: "pma.campus"
        VIRTUAL_PORT: 80
    depends_on:
      - proxy

  nginx:
    container_name: campus-nginx
    image: campus-nginx:1.0.0
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./public/:/www/public
    environment:
      VIRTUAL_HOST: "campus.localhost"
      VIRTUAL_PORT: 80
    depends_on:
      - proxy

  fpm:
    container_name: campus-fpm
    image: campus-fpm:1.0.1
    build:
      context: ./docker/fpm
      dockerfile: ./Dockerfile
    env_file:
      - ./docker/.env
    volumes:
      - ./:/www
